package factoryMethod;

public class Client {
	public static void main(String[] args) {
	PasajeEstandar pasajeEstandar = new PasajeEstandar();
	Destino destino= new Destino();
	destino.setPais("Eslovenia");
	destino.setCiudad("Liubliana");
	destino.setAeropuerto("Aeropuerto de Liubliana");
	pasajeEstandar.setDestino(destino);
	Origen origen = new Origen();
	origen.setPais("Republica Dominicana");
	origen.setCiudad("Punta Cana");
	origen.setAeropuerto("La Romana");
	pasajeEstandar.setOrigen(origen);
	Avion avion = new Avion();
	avion.setMarca("BOA");
	avion.setCapacidad("300");
	avion.setModelo("RJ 546");
	avion.setNumeroAsientos("300");
	pasajeEstandar.setAvion(avion);
	Pasajero pasajero = new Pasajero();
	pasajero.setNombre("Ricardo Sauma");
	pasajero.setCi("23154876");
	pasajeEstandar.setPasajero(pasajero);
	pasajeEstandar.setNumeroAsiento("46");
	pasajeEstandar.setCostoPasaje("450 bs");
	pasajeEstandar.create();
	
	PasajeEstandar pasajeEstandar2 = new PasajeEstandar();
	Destino destino2= new Destino();
	destino2.setPais("Rusia");
	destino2.setCiudad("Moscu");
	destino2.setAeropuerto("Sheremétievo");
	pasajeEstandar2.setDestino(destino);
	Origen origen2 = new Origen();
	origen2.setPais("Brasil");
	origen2.setCiudad("Rio De Janeiro");
	origen2.setAeropuerto("Antônio Carlos Jobim");
	pasajeEstandar2.setOrigen(origen);
	Avion avion2 = new Avion();
	avion2.setMarca("American Airlines");
	avion2.setCapacidad("500");
	avion2.setModelo("JA 8461");
	avion2.setNumeroAsientos("500");
	pasajeEstandar2.setAvion(avion);
	Pasajero pasajero2 = new Pasajero();
	pasajero2.setNombre("Juan Martinez");
	pasajero2.setCi("56876165");
	pasajeEstandar2.setPasajero(pasajero);
	pasajeEstandar2.setNumeroAsiento("64");
	pasajeEstandar2.setCostoPasaje("800 bs");
	pasajeEstandar2.create();
	
	PasajeSolidario pasajeSolidario = new PasajeSolidario();
	Destino destino3= new Destino();
	destino3.setPais("Japon");
	destino3.setCiudad("Tokio");
	destino3.setAeropuerto("Narita");
	pasajeSolidario.setDestino(destino);
	Origen origen3 = new Origen();
	origen3.setPais("Kenia");
	origen3.setCiudad("Nairobi");
	origen3.setAeropuerto("Jomo Kenyatta");
	pasajeSolidario.setOrigen(origen);
	Avion avion3 = new Avion();
	avion3.setMarca("American Airlines");
	avion3.setCapacidad("500");
	avion3.setModelo("JA 8461");
	avion3.setNumeroAsientos("500");
	pasajeSolidario.setAvion(avion);
	Pasajero pasajero3 = new Pasajero();
	pasajero3.setNombre("Pedro Licona");
	pasajero3.setCi("56876165");
	pasajeSolidario.setPasajero(pasajero);
	pasajeSolidario.setNumeroAsiento("64");
	pasajeSolidario.setCostoPasaje("800 bs");
	pasajeSolidario.setDescuento("200 bs");
	pasajeSolidario.setMotivoDescuento("Discapacidad");
	pasajeSolidario.create();
	
	PasajeSolidario pasajeSolidario2 = new PasajeSolidario();
	Destino destino4= new Destino();
	destino4.setPais("Italia");
	destino4.setCiudad("Palermo");
	destino4.setAeropuerto("Punta Raisi");
	pasajeSolidario2.setDestino(destino);
	Origen origen4 = new Origen();
	origen4.setPais("Alemania");
	origen4.setCiudad("Berlin");
	origen4.setAeropuerto("Tempelhof");
	pasajeSolidario2.setOrigen(origen);
	Avion avion4 = new Avion();
	avion4.setMarca("Avianca");
	avion4.setCapacidad("500");
	avion4.setModelo("JA 8461");
	avion4.setNumeroAsientos("500");
	pasajeSolidario2.setAvion(avion);
	Pasajero pasajero4 = new Pasajero();
	pasajero4.setNombre("Pablo Uriarte");
	pasajero4.setCi("54976839");
	pasajeSolidario.setPasajero(pasajero);
	pasajeSolidario.setNumeroAsiento("64");
	pasajeSolidario.setCostoPasaje("800 bs");
	pasajeSolidario.setDescuento("700 bs");
	pasajeSolidario.setMotivoDescuento("Accion Social");
	pasajeSolidario.create();
	
	PasajeInfantes pasajeInfantes = new PasajeInfantes();
	Destino destino5= new Destino();
	destino5.setPais("Noruega");
	destino5.setCiudad("Oslo");
	destino5.setAeropuerto("Gardermoen");
	pasajeInfantes.setDestino(destino);
	Origen origen5 = new Origen();
	origen5.setPais("Colorado");
	origen5.setCiudad("Denver");
	origen5.setAeropuerto("Aeropuerto de Denver");
	pasajeInfantes.setOrigen(origen);
	Avion avion5 = new Avion();
	avion5.setMarca("BOA");
	avion5.setCapacidad("300");
	avion5.setModelo("RJ 546");
	avion5.setNumeroAsientos("300");
	pasajeInfantes.setAvion(avion);
	Pasajero pasajero5 = new Pasajero();
	pasajero5.setNombre("Jorge Ruiz");
	pasajero5.setCi("98756415");
	pasajeInfantes.setPasajero(pasajero);
	pasajeInfantes.setNumeroAsiento("46");
	pasajeInfantes.setCostoEspecial("450 bs");
	pasajeEstandar.create();
	
	PasajeInfantes pasajeInfantes2 = new PasajeInfantes();
	Destino destino6= new Destino();
	destino6.setPais("Croacia");
	destino6.setCiudad("Zabreb");
	destino6.setAeropuerto("Franjo Tudman");
	pasajeInfantes2.setDestino(destino);
	Origen origen6 = new Origen();
	origen6.setPais("Grecia");
	origen6.setCiudad("Atenas");
	origen6.setAeropuerto("Eleftherios Venizelos");
	pasajeInfantes2.setOrigen(origen);
	Avion avion6 = new Avion();
	avion6.setMarca("BOA");
	avion6.setCapacidad("300");
	avion6.setModelo("RJ 546");
	avion6.setNumeroAsientos("300");
	pasajeInfantes2.setAvion(avion);
	Pasajero pasajero6 = new Pasajero();
	pasajero6.setNombre("Julio Cesar");
	pasajero6.setCi("87987466");
	pasajeInfantes2.setPasajero(pasajero);
	pasajeInfantes2.setNumeroAsiento("46");
	pasajeInfantes2.setCostoEspecial("400 bs");
	pasajeEstandar2.create();
	
	
}
}
